# デモ用 MenuIsland
# version: "3"
services:
    app_ms:
        image: nginx
        container_name: app_ms
        ports:
            - "4444:443"
            # - "443:443"
        # working_dir: /usr/src/app
        working_dir: /app
        volumes:
            # - ./src/html:/app
            - ./docs:/app
            # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /usr/src/app/node_modules # コンテナ内のnode_modulesを使用
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/conf/certs:/etc/nginx/certs
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
    # node_gpt:
    #   image: node:17-slim
    #   container_name: node_gpt
    #   tty: true
    #   working_dir: /usr/src/app
    #   volumes:
    #     - /usr/src/app/node_modules # コンテナ内のnode_modulesを使用
    #     - ./app:/usr/src/app
    #     - ./lib:/usr/src/lib           # CommonUtil や ConfigBuilderなどを配置
    #     # - ./work:/usr/src/work
    #   build:
    #     context: .
    #     dockerfile: ./docker/node/Dockerfile
