FROM nginx:latest
# COPY ./etc/.bashrc /root

# ENV PATH $PATH:/usr/src/app/node_modules/.bin
# RUN echo $PATH
# COPY /usr/src/app/scripts/plugin-uploader/dist/index.js /usr/src/app/node_modules/@kintone/plugin-uploader/dist/index.js
# ↑ npm installのあとに実行する

# RUN mkdir /etc/nginx/ssl
# COPY ./docker/nginx/ssl/server.key /etc/nginx/ssl
# COPY ./docker/nginx/ssl/server.crt /etc/nginx/ssl

# COPY ./docker/nginx/ssl/localhost+2.pem /etc/nginx/ssl
# COPY ./docker/nginx/ssl/localhost+2-key.pem /etc/nginx/ssl


# RUN apt-get install -y libgtk-3.0 libgbm-dev libnss3 libatk-bridge2.0-0 libasound2 libxshmfence-dev
