# FROM node:latest
FROM node:17-slim
COPY ./etc/.bashrc /root

# ENV PATH $PATH:/usr/src/app/node_modules/.bin
# RUN echo $PATH
# COPY /usr/src/app/scripts/plugin-uploader/dist/index.js /usr/src/app/node_modules/@kintone/plugin-uploader/dist/index.js
# ↑ npm installのあとに実行する

RUN apt update
RUN apt-get install -y libgtk-3.0 libgbm-dev libnss3 libatk-bridge2.0-0 libasound2 libxshmfence-dev
# RUN npm install
